/**
 * generated by Xtext 2.25.0
 */
package diazdecerio.mydsl.myDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Condition</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link diazdecerio.mydsl.myDsl.Condition#getReg <em>Reg</em>}</li>
 *   <li>{@link diazdecerio.mydsl.myDsl.Condition#getNumber <em>Number</em>}</li>
 * </ul>
 *
 * @see diazdecerio.mydsl.myDsl.MyDslPackage#getCondition()
 * @model
 * @generated
 */
public interface Condition extends EObject
{
  /**
   * Returns the value of the '<em><b>Reg</b></em>' attribute.
   * The literals are from the enumeration {@link diazdecerio.mydsl.myDsl.Register}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Reg</em>' attribute.
   * @see diazdecerio.mydsl.myDsl.Register
   * @see #setReg(Register)
   * @see diazdecerio.mydsl.myDsl.MyDslPackage#getCondition_Reg()
   * @model
   * @generated
   */
  Register getReg();

  /**
   * Sets the value of the '{@link diazdecerio.mydsl.myDsl.Condition#getReg <em>Reg</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Reg</em>' attribute.
   * @see diazdecerio.mydsl.myDsl.Register
   * @see #getReg()
   * @generated
   */
  void setReg(Register value);

  /**
   * Returns the value of the '<em><b>Number</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Number</em>' attribute.
   * @see #setNumber(int)
   * @see diazdecerio.mydsl.myDsl.MyDslPackage#getCondition_Number()
   * @model
   * @generated
   */
  int getNumber();

  /**
   * Sets the value of the '{@link diazdecerio.mydsl.myDsl.Condition#getNumber <em>Number</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Number</em>' attribute.
   * @see #getNumber()
   * @generated
   */
  void setNumber(int value);

} // Condition
