/**
 * generated by Xtext 2.25.0
 */
package diazdecerio.mydsl.myDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Constructor</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link diazdecerio.mydsl.myDsl.Constructor#getConstructor <em>Constructor</em>}</li>
 *   <li>{@link diazdecerio.mydsl.myDsl.Constructor#getStmts <em>Stmts</em>}</li>
 * </ul>
 *
 * @see diazdecerio.mydsl.myDsl.MyDslPackage#getConstructor()
 * @model
 * @generated
 */
public interface Constructor extends EObject
{
  /**
   * Returns the value of the '<em><b>Constructor</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Constructor</em>' reference.
   * @see #setConstructor(JavaClass)
   * @see diazdecerio.mydsl.myDsl.MyDslPackage#getConstructor_Constructor()
   * @model
   * @generated
   */
  JavaClass getConstructor();

  /**
   * Sets the value of the '{@link diazdecerio.mydsl.myDsl.Constructor#getConstructor <em>Constructor</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Constructor</em>' reference.
   * @see #getConstructor()
   * @generated
   */
  void setConstructor(JavaClass value);

  /**
   * Returns the value of the '<em><b>Stmts</b></em>' containment reference list.
   * The list contents are of type {@link diazdecerio.mydsl.myDsl.Stmt}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Stmts</em>' containment reference list.
   * @see diazdecerio.mydsl.myDsl.MyDslPackage#getConstructor_Stmts()
   * @model containment="true"
   * @generated
   */
  EList<Stmt> getStmts();

} // Constructor
