/**
 * generated by Xtext 2.25.0
 */
package diazdecerio.mydsl.myDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Main</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link diazdecerio.mydsl.myDsl.Main#getTheType <em>The Type</em>}</li>
 *   <li>{@link diazdecerio.mydsl.myDsl.Main#getAgain <em>Again</em>}</li>
 * </ul>
 *
 * @see diazdecerio.mydsl.myDsl.MyDslPackage#getMain()
 * @model
 * @generated
 */
public interface Main extends EObject
{
  /**
   * Returns the value of the '<em><b>The Type</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>The Type</em>' reference.
   * @see #setTheType(JavaClass)
   * @see diazdecerio.mydsl.myDsl.MyDslPackage#getMain_TheType()
   * @model
   * @generated
   */
  JavaClass getTheType();

  /**
   * Sets the value of the '{@link diazdecerio.mydsl.myDsl.Main#getTheType <em>The Type</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>The Type</em>' reference.
   * @see #getTheType()
   * @generated
   */
  void setTheType(JavaClass value);

  /**
   * Returns the value of the '<em><b>Again</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Again</em>' reference.
   * @see #setAgain(JavaClass)
   * @see diazdecerio.mydsl.myDsl.MyDslPackage#getMain_Again()
   * @model
   * @generated
   */
  JavaClass getAgain();

  /**
   * Sets the value of the '{@link diazdecerio.mydsl.myDsl.Main#getAgain <em>Again</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Again</em>' reference.
   * @see #getAgain()
   * @generated
   */
  void setAgain(JavaClass value);

} // Main
