/**
 * generated by Xtext 2.25.0
 */
package diazdecerio.mydsl.myDsl;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>While Stmt</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link diazdecerio.mydsl.myDsl.WhileStmt#getCond <em>Cond</em>}</li>
 *   <li>{@link diazdecerio.mydsl.myDsl.WhileStmt#getStmtsWhile <em>Stmts While</em>}</li>
 * </ul>
 *
 * @see diazdecerio.mydsl.myDsl.MyDslPackage#getWhileStmt()
 * @model
 * @generated
 */
public interface WhileStmt extends Stmt
{
  /**
   * Returns the value of the '<em><b>Cond</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Cond</em>' containment reference.
   * @see #setCond(Condition)
   * @see diazdecerio.mydsl.myDsl.MyDslPackage#getWhileStmt_Cond()
   * @model containment="true"
   * @generated
   */
  Condition getCond();

  /**
   * Sets the value of the '{@link diazdecerio.mydsl.myDsl.WhileStmt#getCond <em>Cond</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Cond</em>' containment reference.
   * @see #getCond()
   * @generated
   */
  void setCond(Condition value);

  /**
   * Returns the value of the '<em><b>Stmts While</b></em>' containment reference list.
   * The list contents are of type {@link diazdecerio.mydsl.myDsl.Stmt}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Stmts While</em>' containment reference list.
   * @see diazdecerio.mydsl.myDsl.MyDslPackage#getWhileStmt_StmtsWhile()
   * @model containment="true"
   * @generated
   */
  EList<Stmt> getStmtsWhile();

} // WhileStmt
