/*
 * generated by Xtext 2.25.0
 */
package diazdecerio.mydsl.ui.tests;

import com.google.inject.Injector;
import diazdecerio.mydsl.ui.internal.MydslActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class MyDslUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return MydslActivator.getInstance().getInjector("diazdecerio.mydsl.MyDsl");
	}

}
